version: '3'

services:

  agora:
    image: "mukeunkim/agora:latest"
    ports:
      - "2826:2826"
      - "2827:2827"
      - "9111:9111"
    volumes:
      - "./agora/:/agora/"

  mysql:
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./stoa/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"

  stoa:
    image: "mukeunkim/stoa:latest"
    depends_on:
      - "agora"
      - "mysql"
    ports:
      - "3836:3836"
    volumes:
      - "./stoa/:/stoa/wd/"

  sendtx:
    image: "mukeunkim/sendtx:latest"
    depends_on:
      - "agora"
      - "stoa"
    volumes:
      - "./sendtx/:/sendtx/wd/"
