node:
  testing: true
  limit_test_validators: 1

  # You might want to change this
  block_interval_sec: 120

  address:       0.0.0.0
  port:          2826

  min_listeners: 0
  max_listeners: 10
  retry_delay:   500
  max_retries:   25
  timeout:       2000
  data_dir: .cache
  preimage_reveal_interval: 100

  tx_payload_max_size: 1024
  tx_payload_fee_factor: 200

consensus:
  validator_cycle: 20

banman:
  max_failed_requests: 10
  ban_duration: 86400

admin:
  enabled: true      # `false` by default
  address: 0.0.0.0   # Private
  port:    2827      # 0xB0B

validator:
  enabled: true
  # NODE6 is first in the list of enrollments
  seed: SAUHVPR7O7F2QGLDVXG3DQTVHXESE3ZAWHIIGKT35LCHIPLZBZTAFXJA
  registry_address: disabled

################################################################################
##                             Flash configuration                            ##
## Configuration options for the Flash functionality of the node.             ##
##                                                                            ##
################################################################################
flash:
  # Whether or not the Flash protocol should be supported
  enabled: false
  # Timeout for each request in milliseconds
  timeout: 10000
  # This is a randomly generated keypair
  # DO NOT USE THOSE VALUES ANYWHERE
  # Private seed:    SCT4KKJNYLTQO4TVDPVJQZEONTVVW66YLRWAINWI3FZDY7U4JS4JJEI4
  # Public address:  GCOQEOHAUFYUAC6G22FJ3GZRNLGVCCLESEJ2AXBIJ5BJNUVTAERPLRIJ
  seed: SAUHVPR7O7F2QGLDVXG3DQTVHXESE3ZAWHIIGKT35LCHIPLZBZTAFXJA

  # Address to the listener which will receive payment / update notifications
  listener_address: http://127.0.0.1:4004

  # Minimum funding allowed for a channel to be opened (in BOA)
  min_funding: 0

  # Maximum funding allowed for a channel to be opened (in BOA)
  max_funding: 100000

  # Minimum number of blocks before settling can begin after a trigger
  # transaction has been published
  min_settle_time: 6

  # Maximum number of blocks afte which settling can begin after a trigger
  # transaction has been published
  max_settle_time: 144

  # Maximum number of seconds to re-try a failed payment / update request
  # before the request is considered failed and is reported to the listener
  # (wallet / etc)
  max_retry_time: 60

network:
  # Supported value: IPv4, IPv6
  - http://node-1:2826
  -

dns:
  # Supported value: FQDN seed
  - seed.bosagora.io

# You might want to change this to one of:
# Trace, Info, Warn, Error, Fatal, None (default)
logging:
  root:
    level: Info

event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  block_externalized:
    - http://stoa:3836/block_externalized
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  preimage_received:
    - http://stoa:3836/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  transaction_received:
    - http://stoa:3836/transaction_received
