node:
  testing: true
  limit_test_validators: 1

  # You might want to change this
  block_interval_sec: 120

  address:       0.0.0.0
  port:          2826

  min_listeners: 0
  max_listeners: 10
  retry_delay:   500
  max_retries:   25
  timeout:       2000
  data_dir: .cache
  preimage_reveal_interval: 100

  tx_payload_max_size: 1024
  tx_payload_fee_factor: 200

consensus:
  validator_cycle: 20

banman:
  max_failed_requests: 10
  ban_duration: 86400

admin:
  enabled: true      # `false` by default
  address: 0.0.0.0   # Private
  port:    2827      # 0xB0B

validator:
  enabled: true
  # NODE6 is first in the list of enrollments
  seed: SDV3GLVZ6W7R7UFB2EMMY4BBFJWNCQB5FTCXUMD5ZCFTDEVZZ3RQ2BZI
  registry_address: disabled

network:
  # Supported value: IPv4, IPv6
  - http://node-1:2826
  -
# You might want to change this to one of:
# Trace, Info, Warn, Error, Fatal, None (default)
logging:
  level: Info

event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  block_externalized:
    - http://stoa:3836/block_externalized
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  preimage_received:
    - http://stoa:3836/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  transaction_received:
    - http://stoa:3836/transaction_received
