#
# This configuration file is intended to provide a standalone local network
# with a single validator.
#
# This configuration is provided for the convenience of developers and should
# not be used in production. See `doc/config.example.yaml` for a full,
# up to date example of the configuration options available
#
# Run from the root with:
# ./build/agora -c devel/config-single.yaml

node:
  testing: true
  limit_test_validators: 1
  block_interval_sec: 5
  data_dir: .cache
  # Can be used with curl or just a browser
  stats_listening_port: 9111

interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826

consensus:
  validator_cycle: 20

validator:
  enabled: true
  # We use first of Genesis Block enrollments: val7: boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh
  seed: SAWI3JZWDDSQR6AX4DRG2OMS26Y6XY4X2WA3FK6D5UW4WTU74GUQXRZP
  registry_address: disabled

admin:
  enabled: true
  address: 0.0.0.0
  port:    2827

# The node will self-ban but this section needs at least one entry
network:
  - http://agora:2826/

# You might want to change this to one of:
# Trace, Info, Warn, Error, Fatal, None (default)
logging:
  root:
    level: Info
    console: true
    propagate: true
    file: log/root.log

  agora.node.Ledger:
    level: Trace
    console: true
    file: log/ledger.log

  agora.consensus.EnrollmentManager:
    level: Trace
    console: false
    file: log/enrollment_manager.log

  agora.consensus.protocol.Nominator:
    level: Trace
    console: false
    file: log/nominator.log

  SCP:
    level: Trace
    console: false
    propagate: true
    file: log/scp.log

event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  block_externalized:
    - http://stoa:3836/block_externalized
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  preimage_received:
    - http://stoa:3836/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  transaction_received:
    - http://stoa:3836/transaction_received
